language: node_js
dist: xenial
node_js:
  - 8
  - 4
  - 6
  - 10
  - node
sudo: false
cache: npm
notifications:
  email: false
  slack:
    secure: Ms5NpfsH+acxe2iULh+z4lQ8U+zLMNylcQCDUc1oAY+2ubjdFsyuw4fDeAN0NdquDD6GEPPD1XF1aZBjWJRNe7bmVCUnu9QAspvuIHOHrikJYunz6so5Fsh2pr96zdJRDnNk3Xu0oMMNhYdh/qpIHpu/GOEkJW+BGDCUntudc+0=
before_install:
- npm i -g npm@^2.0.0
- npm i -g pangyp
- npm prune
install:
- npm install --node-gyp=$(which pangyp)
before_script:
- curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
after_failure:
- python travis_after_all.py
- export $(cat .to_export_back)
before_deploy:
- rm -f travis_after_all.py .to_export_back
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
deploy:
  provider: npm
  email: david@excellenteasy.com
  skip_cleanup: true
  on:
    branch: master
    repo: excellenteasy/android-splash-generate
    condition: "$BUILD_LEADER$BUILD_AGGREGATE_STATUS = YESothers_succeeded"
  api_key:
    secure: DcLCvKwnYudLFrbxBrPc6ahYc+Lqxoe2K0qKw9/cICllebQuQL6MLGQq+GNsfQ9ACmL1SMpsK1/AF9D+wazyuCDSKfqmuh5QYxWYurkdjyYjstzt5FQRPv8wZS+tuVG5krSNS4TGe8P8lNAne3A+fYBPcj81St9aHrhuNATtpik=
env:
  global:
    secure: cqfjULv++BhPCcTbB4SgnN2rRQfajryycbXxOrfTwvAk/kGhCU5UzLb84zdhaRVKXLksThjgBtd6KV5OFFluBAVCpxDUOE+IbZeFIcuPGHl4433fa1NgDzYcPtY5MsTYNIfNDVtnGSzcgewwAT8pE+AM3N2/JrFwjOC1+efR9FA=
