language: node_js
notifications:
  email: false
dist: bionic
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
    - node_js: node
    - node_js: lts/*
node_js:
  - 6
  - 8
  - 10
  - 12
  - lts/*
  - node
before_deploy:
- git config --local user.name "$TRAVIS_AUTHOR_NAME"
- git config --local user.email "$TRAVIS_AUTHOR_EMAIL"
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
    node: 10
    os: linux
sudo: false
env:
  global:
  - secure: pDk/asMOWbfTz9zZG/BC11LRweqEVM84evm37TFi5lm3vNuCOFz/L4aeXjzUv19XYhcId2BysoJBV5cuuOwNVxvCMAWQ91jGkXIedhLeavY+PB18OK6KDPlhfUL2chigZUV3u5aEglyUbl+/+5/Z4XU5PIGWoEZWqeOXykQMbqzvJR/W8/LdhhbQHqLl/qWOaJ5eHAsd+kgQEA0z6xSFtd+HqT6pHYgljTCtw/VSQpSi9hRFWGrjwPEfuEaMOlwCtexRzoQf0xhcM1Pt7AKLchpLjshjgi+7E8ZTwHI/29OIAAmSrLe+6IwKd8k0ayTN10I63mqZmDtiDEH+1YX392WndFgfPso0Ne3hXR8Eiaa6aQ1LLKJFSr9MEOPG5bwHKBmYDCp78G4KvvDKLYplhnTEiXb/c26//Kblkej1x2rzyd/YXd+r86yRpI4ph4VLN/pmVnoEA2z0rTypujx7P0H3YpiqkXcv896dNvH0LiEh1VSErRZHGc9jfgguEg8Rcy0e93VH2/kKpu7YbW3R7RWMqUz8c1PfKVrGBVyZBhtyXMyJGixdmBKKkjjDub5+EfL4nyHV/6P2jNbXvXS4/QK350f8s8CPtQx70ZGxk2443nugD9w1zeTfdwRjgp/nhBrtUo9mUCQXaXFvLs/I4xddxIke/mZLBVm5WQQLpds=
  - secure: YQ3ZoYZg2PA6qWafrW+gpKbWX0V7dXYf2HiEdf6B5jhCcX7ZC60faE/6pBxSz4jq5JqInNVvKFyaXX09SzyyI73coXQMSFLohp+Z+kk7XEl2+X7OXqa/aBtrHcXKg7WU55OPohtM9xZ1HYcusun1sib0S1Hlruc+hTU/mHZvDzXlgEy9poMb9gEhNZxhpr2AQvXGwiu9GIoZaMzx//M3XykfxMbN9GW3wN+FW/DVZo8ouskA7dakAYcWkCMqIjy86XeL9Zbg3zWsY4jJIpq7ZwcQHp2etUEZiwsP6Vezip7mk0iQpbcsRbmSU8JCenxfVPSPIsv604wdBlIS+UILEyi2qPi2Hfh2rtmFkEDJW1B01ukhBnYRDXzmqFLRjGgGCZJpa/SCEIJmQkhLVavA7TB2CQ5Qft2UP5WTy0cBzFWhICOAUfYscAlGs08HVfyobw0ngHG8jV/qUMV7rQE8BfECl4msVuqVU1GIZdFFfMV9NzW9M95Yuo+YrVPWoKRd2UXdXjUVzzGWZ75MOsw3y9TqR2DLWCYEbBTq5lKUDf2sQUpxAkMCWZHyCol6y1lOUrnshudLee0v+DunqbEGD2ohigfTwUOtMjX3Lw9kukXCYeA8zo6T83tSUQFDgXAg+lSCJ4oe1wMWjiz9U5vPvALEY96LVfGwr2MD36SaRUU=
